import { test as base } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { BondCreationPage } from '../pages/BondCreationPage';
import { BondDetailPage } from '../pages/BondDetailPage';
import { DashboardPage } from '../pages/DashboardPage';
import { LoginPage } from '../pages/LoginPage';
import { ProfileMenu } from '../pages/ProfileMenu';
import { getBaseUrl } from '../utils/environment';

export type QaFixtures = {
  loginPage: LoginPage;
  dashboardPage: DashboardPage;
  profileMenu: ProfileMenu;
  bondCreationPage: BondCreationPage;
  bondDetailPage: BondDetailPage;
  authenticatedSession: void;
  failureScreenshot: void;
};

const errorScreenshotDirectory = path.resolve(__dirname, '../../screenshots/Errors');

export const test = base.extend<QaFixtures>({
  failureScreenshot: [
    async ({ page }, use, testInfo) => {
      await use();
      if (testInfo.status === testInfo.expectedStatus || page.isClosed()) return;

      const name = `${testInfo.title}-${testInfo.project.name}-attempt-${testInfo.retry + 1}`
        .replace(/[^A-Za-z0-9-]+/g, '-')
        .replace(/-+/g, '-')
        .slice(0, 150);
      const screenshotPath = path.join(errorScreenshotDirectory, `${name}.png`);
      await page.screenshot({ path: screenshotPath, fullPage: true });
      await testInfo.attach('failure-screenshot', { path: screenshotPath, contentType: 'image/png' });
    },
    { auto: true },
  ],
  loginPage: async ({ page }, use) => use(new LoginPage(page)),
  dashboardPage: async ({ page }, use) => use(new DashboardPage(page)),
  profileMenu: async ({ page }, use) => use(new ProfileMenu(page)),
  bondCreationPage: async ({ page }, use) => use(new BondCreationPage(page)),
  bondDetailPage: async ({ page }, use) => use(new BondDetailPage(page)),
  // The authenticated Chromium project loads storageState generated by global setup.
  authenticatedSession: async ({ page, dashboardPage }, use) => {
    const sessionStorageFile = path.resolve(__dirname, '../../playwright/.auth/session-storage.json');
    const sessionStorage = JSON.parse(await readFile(sessionStorageFile, 'utf8')) as Record<string, string>;
    const origin = getBaseUrl();
    await page.addInitScript(({ expectedOrigin, entries }) => {
      if (window.location.origin === expectedOrigin) {
        for (const [key, value] of Object.entries(entries)) {
          window.sessionStorage.setItem(key, value);
        }
      }
    }, { expectedOrigin: origin, entries: sessionStorage });
    await page.goto('/', { waitUntil: 'domcontentloaded' });
    await dashboardPage.assertDashboardReady();
    await use();
  },
});

export { expect } from '@playwright/test';
