import { test as base } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { BondCreationPage } from '../pages/BondCreationPage';
import { DashboardPage } from '../pages/DashboardPage';
import { LoginPage } from '../pages/LoginPage';
import { ProfileMenu } from '../pages/ProfileMenu';
import { getRequiredEnvironmentVariable } from '../utils/environment';

export type QaFixtures = {
  loginPage: LoginPage;
  dashboardPage: DashboardPage;
  profileMenu: ProfileMenu;
  bondCreationPage: BondCreationPage;
  authenticatedSession: void;
};

export const test = base.extend<QaFixtures>({
  loginPage: async ({ page }, use) => use(new LoginPage(page)),
  dashboardPage: async ({ page }, use) => use(new DashboardPage(page)),
  profileMenu: async ({ page }, use) => use(new ProfileMenu(page)),
  bondCreationPage: async ({ page }, use) => use(new BondCreationPage(page)),
  // The authenticated Chromium project loads storageState generated by global setup.
  authenticatedSession: async ({ page, dashboardPage }, use) => {
    const sessionStorageFile = path.resolve(__dirname, '../../playwright/.auth/session-storage.json');
    const sessionStorage = JSON.parse(await readFile(sessionStorageFile, 'utf8')) as Record<string, string>;
    const origin = new URL(getRequiredEnvironmentVariable('URL').trim()).origin;
    await page.addInitScript(({ expectedOrigin, entries }) => {
      if (window.location.origin === expectedOrigin) {
        for (const [key, value] of Object.entries(entries)) {
          window.sessionStorage.setItem(key, value);
        }
      }
    }, { expectedOrigin: origin, entries: sessionStorage });
    await page.goto('/', { waitUntil: 'domcontentloaded' });
    await dashboardPage.assertDashboardReady();
    await use();
  },
});

export { expect } from '@playwright/test';
